apiVersion: apps/v1
kind: Deployment
metadata:
  name: hab-load-deployment
  labels:
    app: hab-load
spec:
  replicas: 100
  selector:
    matchLabels:
      app: hab-load
  template:
    metadata:
      labels:
        app: hab-load
    spec:
      containers:
      - name: hab-load
        image: irvingpop/hab_load:latest
        args:
        - --topology
        - standalone
        - --peer
        - hab-bastion-1
        - --peer
        - hab-bastion-2
        - --peer
        - hab-bastion-3
        resources:
          requests:
            memory: "300Mi"
            cpu: "50m" # equivalent to 0.05 of a CPU core
        # env:
        # - name: HAB_LOAD
        #   value: |
        #     protected-mode = 'no'
        # ports:
        # - containerPort: 6379
