apiVersion: apps/v1
kind: Deployment
metadata:
  name: hab-load-deployment
  labels:
    app: hab-load
spec:
  replicas: 100
  selector:
    matchLabels:
      app: hab-load
  template:
    metadata:
      labels:
        app: hab-load
    spec:
      containers:
      - name: hab-load
        image: irvingpop/hab_load:0.2.1-20181119185646
        args:
        - --topology
        - standalone
        - --peer
        - hab-bastion-1
        # - --peer
        # - hab-bastion-2
        # - --peer
        # - hab-bastion-3
        resources:
          requests:
            memory: "300Mi"
            cpu: "50m" # equivalent to 0.05 of a CPU core
        env:
        - name: RUST_BACKTRACE
          value: "1"
        - name: HAB_SUP_BINARY
          value: /hab/pkgs/irvingpop/hab-sup/0.69.0-dev/20181119183900/bin/hab-sup
        # readinessProbe:
        # env:
        # - name: HAB_LOAD
        #   value: |
        #     protected-mode = 'no'
        # ports:
        # - containerPort: 6379
